### ISSUE TITLE
2.6.1版本下,连锁导致崩档,重启客户端才可进入存档.

### ISSUE THREAD

**Issue by FurnaceGT** [QuanhuZeYu/Qz-Miner#1]
如题,崩溃后任何存档都进入不了,一直卡在进入界面,重启客户端后才可进入,进入后连锁并未生效,即只挖掘了一个方块.
https://mclo.gs/eHDSs95
[Uploading latest.log…]()

**Comment by FurnaceGT** [comment]
连锁版本:1.2.0

**Comment by QuanhuZeYu** [comment]
[v1.2.1](https://github.com/QuanhuZeYu/Qz-Miner/releases/tag/v1.2.1l)

新版本已经修复270以下的兼容性问题
