### ISSUE TITLE
连锁GT设备时常见错误

### ISSUE THREAD

**Issue by PinkYuDeer** [QuanhuZeYu/Qz-Miner#10]
1、连锁电线时会把能源仓干掉：
![image](https://github.com/user-attachments/assets/04353f17-45e7-4a04-bdea-59fbc3c3fe11)

2、连锁激光时会把主机方块、输入输出仓、维护仓、激光仓干掉：
![image](https://github.com/user-attachments/assets/0b5bc921-4f0c-4c6f-9753-348cac89a9b3)

另外，佬是否可以增加一个隐藏当前连锁状态提示的配置选项？
![image](https://github.com/user-attachments/assets/085f6b65-53f9-456d-863f-2d8e977fb14a)

**Comment by PinkYuDeer** [comment]
![image](https://github.com/user-attachments/assets/3ecce165-f628-4113-af3b-19b86ed71362)
一扳手一基地名不虚传.jpg

**Comment by QuanhuZeYu** [comment]
beta.4新增了严格连锁模式，你可以尝试一下是否符合预期，如果还有问题或者改进建议请在此继续反馈。隐藏指示器暂不考虑，或者会考虑做成一个有颜色的圆圈以节省屏幕空间

**Comment by PinkYuDeer** [comment]
![775624e3d49cf6476c13c69883800fee](https://github.com/user-attachments/assets/5b0fab14-aee4-45fd-aa9a-14b0ed2fc884)
非常好严格模式，爱来自小鹿。

于此同时发现了一个bug还是预期行为的现象，距离目标超过两格左右尝试连锁的时候，不会进行渲染。

**Comment by QuanhuZeYu** [comment]
if (playerPos.distanceSquared(new Vector3d(curCenter)) > 16) {
                return;
}
超过距离不进行渲染是预期行为，我等会改成配置项好了
