### ISSUE TITLE
[BUG]客户端尝试连锁时大量报错导致卡顿。

### ISSUE THREAD

**Issue by PinkYuDeer** [QuanhuZeYu/Qz-Miner#11]
不影响正常连锁，报错如下：（版本：gtnh-2.7.1-Java21）
[QzMinerThreadPool-3/WARN] [qz_miner]: 检查是否可以挖掘时出现异常: java.lang.ClassCastException: class net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to class net.minecraft.entity.player.EntityPlayerMP
完整日志：[log.txt](https://github.com/user-attachments/files/18217853/log.txt)

**Comment by QuanhuZeYu** [comment]
beta.4尝试修复了这个问题，请下载尝试，如果还有问题请在此继续反馈

**Comment by PinkYuDeer** [comment]
非常好beta.4，爱来自小鹿
