### ISSUE TITLE
游戏内无法使用qz_m指令

### ISSUE THREAD

**Issue by OchiaiNao** [QuanhuZeYu/Qz-Miner#12]
![d7068465-65ec-4120-b2ad-3b61df23bcd1](https://github.com/user-attachments/assets/ada046d0-260d-468b-8ac7-05e49dd15af5)
服务器:2.7.0-java8, qz-miner版本1.9.0-beta3

**Comment by OchiaiNao** [comment]
![0339b55d-e347-4b0d-a20f-a39634087a15](https://github.com/user-attachments/assets/d928794a-1bd9-4bc2-97aa-535823f29dae)
补一张游戏内打qz_m的截图
![98399086b3374b89430a062f40c2c8c0](https://github.com/user-attachments/assets/68f269ee-a0dd-4c74-834b-4d0a612f3bd4)

**Comment by QuanhuZeYu** [comment]
beta.4尝试修复了这个问题，请下载尝试，如果还有问题请在此继续反馈

**Comment by OchiaiNao** [comment]
已解决

**Comment by OchiaiNao** [comment]
使用游戏内置/qz_m指令设置超过范围的数值：例如 RenderTime=0，会导致生成一个超过最低值的float。 此时会类型转换错误

![a1d25789-e707-4d1d-9589-6fd3923dd210](https://github.com/user-attachments/assets/0fe125f9-924d-412c-a523-ba3f55aad082)

游戏内提示错误同上

**Comment by QuanhuZeYu** [comment]
指令格式为 /qz_m setx value，v1.9.1调整了取值范围，rendertime可以设置为-1
