### ISSUE TITLE
无法连锁挖掘“雪”

### ISSUE THREAD

**Issue by Nxer** [QuanhuZeYu/Qz-Miner#14]
![image](https://github.com/user-attachments/assets/b8148616-5007-4578-a2af-440901744272)

**Comment by QuanhuZeYu** [comment]
要不你试试铲子（，猜测应该是canHarvest函数没通过，手拍没有掉落物没给过

**Comment by Nxer** [comment]
> 要不你试试铲子（，猜测应该是canHarvest函数没通过，手拍没有掉落物没给过

雪 方块没有被破坏是最主要的

**Comment by QuanhuZeYu** [comment]
![image](https://github.com/user-attachments/assets/71adcffa-2a36-4846-afc4-1ea7e77edab7)
这俩玩意确实不一样，也没继承关系，只能硬编码进去了

**Comment by QuanhuZeYu** [comment]
v1.10.0加了一个宽松模式，只要掉落物是相同的就会被判定连锁，等自动构建好试试吧
