### ISSUE TITLE
更新到1.10.2连锁出了奇怪的问题

### ISSUE THREAD

**Issue by Suzumi999** [QuanhuZeYu/Qz-Miner#17]
https://github.com/user-attachments/assets/1d5623ce-4f36-470e-89fd-8d2d465c7d40

像视频里这样，我也不太知道怎么表达。

连锁速度变的很慢，而且需要一直按着开关键。
左下角弹出错误后，连锁也并没有停止。

**Comment by Suzumi999** [comment]
![image](https://github.com/user-attachments/assets/4bea61a6-a056-47db-8ef2-cf05fdec5efb)
我的配置文件，其他没有更改

**Comment by QuanhuZeYu** [comment]
v1.10.3修复了挖掘速度的问题，这是v1.10.0修改程序逻辑时出现的小问题
