### ISSUE TITLE
佬可以新增对普通方块的连锁吗（ae仅连锁管道之类的）

### ISSUE THREAD

**Issue by PinkYuDeer** [QuanhuZeYu/Qz-Miner#3]
如果这样的话 直接拳打vein脚踏oree

**Comment by QuanhuZeYu** [comment]
挖TileEntity有一定风险, 有些特殊一点的TileEntity例如多方块机器之类的可能会产生崩溃, 后面我试一下吧

**Comment by QuanhuZeYu** [comment]
1.7.0版本现在支持实体方块连锁，注意实体破坏仅在连锁模式分类下，爆破模式不支持实体破坏，防止拆家悲剧

**Comment by PinkYuDeer** [comment]
太牛了 我想把您的mod推荐到GTNH wiki可安装mod列表中，并附上github连接，可以吗
