### ISSUE TITLE
一些功能建议，希望能考虑添加下

### ISSUE THREAD

**Issue by hbwbf** [QuanhuZeYu/Qz-Miner#4]
1. 在mod list里添加游戏内直接修改config的功能
2. 在控制里添加修改热键的功能
3. 添加饱食度消耗调整功能
上面是我照着ore excavation提的比较方便一些的功能，希望能给大佬做个参考

**Comment by haobawobufu** [comment]
抱歉，刚发现2已经有了。
此外希望大佬能添加一个用户手动配置连锁方块分组的功能，例如ore excavation就有一个oreexcavation_groups.json的配置文件，用户可以根据矿物词典来设置自己的连锁方块的分组。

**Comment by QuanhuZeYu** [comment]
1.8.3之后的版本已经经过测试确定添加的功能有效，请使用1.8.3之后的版本
