### ISSUE TITLE
虚空挖矿bug

### ISSUE THREAD

**Issue by Oncelane** [QuanhuZeYu/Qz-Miner#7]
表现：

不消耗世界实体矿，按键不停爆矿不断，推测是反复挖掘同一片虚空矿物

![QQ图片20241213162257](https://github.com/user-attachments/assets/c2ef5613-32e0-4eb0-9126-aacee6faac17)

连锁挖矿模式+矩形范围

config文件：

```
# Configuration file

general {
    # 一次性最多挖掘数量 [range: 1 ~ 2147483647, default: 128]
    I:blockLimit=12800

    # 连锁模式搜索相邻范围 [range: 1 ~ 6, default: 3]
    I:chainRange=2

    # 每tick挖掘数量 [range: 1 ~ 2147483647, default: 64]
    I:perTickBlockMine=128

    # 连锁遍历点每tick允许搜寻最大时间限制 单位ms [range: 1 ~ 20, default: 5]
    I:pointFonderTaskTimeLimit=5

    # 点位生成器缓存大小, 不建议超过建议最大数值 [range: 1 ~ 10240, default: 4096]
    I:pointFounderCacheSize=4096

    # 挖掘者搜索范围 [range: 1 ~ 2147483647, default: 10]
    I:radiusLimit=1000
}

```

**Comment by QuanhuZeYu** [comment]
看看探矿仪截图，如果真的没挖那确实是bug，范围模式是无连锁逻辑的，它就是简单的遍历整个空间

**Comment by Oncelane** [comment]
![QQ截图20241213165509](https://github.com/user-attachments/assets/f751bcd9-fd41-4ed3-b1f0-a0f59b4e6d99)

忘了说，这个bug只会对贫瘠矿生效，图里也可以看到爆出来的都是贫瘠矿产物，而且只有连锁贫瘠矿时会无视稿子耐久度，完整矿连锁时表现正常，稿子耐久没了就自动停止所以没有这个bug。

图里的贫瘠矿没少，少的那些完整矿是我触发bug后才挖的，跟bug没关系。

**Comment by QuanhuZeYu** [comment]
看你的截图是1.6.1的，换成最新的再试试吧
