### ISSUE TITLE
服务端崩溃问题

### ISSUE THREAD

**Issue by LyeeR0** [QuanhuZeYu/Qz-Miner#8]
按下切换连锁按键(设置为alt)后，服务端会崩溃
版本1.8.2/1.8.5
报错空指针
[crash-2024-12-14_22.36.47-server.txt](https://github.com/user-attachments/files/18136254/crash-2024-12-14_22.36.47-server.txt)
更改键位设置后按下切换连锁键不会崩溃，但挖掘矿物依旧会崩溃

**Comment by LyeeR0** [comment]
更正：切换连锁状态后也会崩溃

**Comment by LyeeR0** [comment]
更正：切换连锁状态后也会崩溃

**Comment by QuanhuZeYu** [comment]
[1.8.5-fix](https://github.com/QuanhuZeYu/Qz-Miner/releases/tag/v1.8.5-fix) 这个版本尝试修复此日志的报错，我的环境下无法复现该错误，推测是有修改聊天栏的模组导致的冲突？请先尝试这个修复版本
